# Generated by Django 5.2.10 on 2026-06-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_movie_id_alter_movie_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
